# Generated by Django 4.1.7 on 2024-02-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='suject',
            new_name='subject',
        ),
    ]
