# Generated by Django 4.1.7 on 2024-02-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0004_remove_diapply_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapply',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
