# Generated by Django 4.1.7 on 2024-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0008_alter_diapply_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapply',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='D:/Leela USA/Leela-Website/Leela/Resume/'),
        ),
    ]
