# Generated by Django 4.1.7 on 2024-02-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0011_ipaapply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ipaapply',
            new_name='Informatica_Programmer_Analyst_Apply',
        ),
    ]
