# Generated by Django 4.1.7 on 2024-02-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0012_rename_ipaapply_informatica_programmer_analyst_apply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diapply',
            new_name='Data_Integration_Engineer',
        ),
    ]
