# Generated by Django 4.1.7 on 2024-02-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0013_rename_diapply_data_integration_engineer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='intern_diapply',
            new_name='Intern_ETL_Developer',
        ),
    ]
