# Generated by Django 4.1.7 on 2024-02-27 06:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0015_data_engineer_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sr_Data_Architect_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=30)),
                ('email2', models.EmailField(max_length=50)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None)),
                ('city2', models.CharField(max_length=30)),
                ('document2', models.FileField(upload_to='Resume/')),
            ],
        ),
    ]
