# Generated by Django 4.1.7 on 2024-02-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0018_it_internship_apply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intern_ETL_Developer',
            new_name='Intern_Etl_Developer_Apply',
        ),
    ]
