# Generated by Django 4.1.7 on 2024-02-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0019_rename_intern_etl_developer_intern_etl_developer_apply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_Integration_Engineer',
            new_name='Data_Integration_Engineer_Apply',
        ),
    ]
