# Generated by Django 4.1.7 on 2024-02-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeelaProject', '0020_rename_data_integration_engineer_data_integration_engineer_apply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_Engineer_apply',
        ),
        migrations.DeleteModel(
            name='Data_Integration_Engineer_Apply',
        ),
        migrations.DeleteModel(
            name='Informatica_Programmer_Analyst_Apply',
        ),
        migrations.DeleteModel(
            name='Intern_Etl_Developer_Apply',
        ),
        migrations.DeleteModel(
            name='IT_Internship_Apply',
        ),
        migrations.DeleteModel(
            name='Solutions_Architect_Apply',
        ),
        migrations.DeleteModel(
            name='Sr_Data_Architect_Apply',
        ),
    ]
